name: Mining

on: [workflow_dispatch]

jobs:
  mine:
    name: Mine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mine
        uses: CDN-Github/xda-min@master
        with:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
